package: linkchecker
version: '0.0.beta'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/linkchecker

page:
    title: translate:linkchecker_title
    perm: linkchecker[params]
    icon: rex-icon fa-chain-broken
    pjax: false
    subpages:
        settings: { title: translate:linkchecker_einstellungen, perm: admin }
        crawler: { title: translate:linkchecker_crawler }
        info: { title: translate:linkchecker_info }

requires:
    redaxo: '^5.5'
